name: Generate changelog on new release

on: [repository_dispatch, workflow_dispatch]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Get pnpm cache path
        id: pnpm-cache
        run: echo "::set-output name=dir::$(pnpm cache dir)"

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Chakra UI version
        run: pnpm deps

      - name: Commit package.json
        run: |
          git add package.json
          git diff --staged --quiet || git commit -m "chore(bump-version): $GITHUB_SHA"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: 'docs: bump chakra version'
          branch: docs/bump-chakra-version
